

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBox;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}

namespace SDKSample
{
    namespace TouchKeyboard
    {
        partial ref class Launch : public ::SDKSample::Common::LayoutAwarePage, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
        
            private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
            private: ::Windows::UI::Xaml::Controls::Grid^ Input;
            private: ::Windows::UI::Xaml::Controls::Grid^ Output;
            private: ::Windows::UI::Xaml::Controls::TextBox^ textBox;
            private: ::Windows::UI::Xaml::VisualState^ FullScreenLandscape;
            private: ::Windows::UI::Xaml::VisualState^ Filled;
            private: ::Windows::UI::Xaml::VisualState^ FullScreenPortrait;
            private: ::Windows::UI::Xaml::VisualState^ Snapped;
        };
    }
}

